{{
    config(
        tags=['mdl_daily']
    )
}}
with
    opp as (select * from {{ ref("sfdc_opportunity") }}),
    oli as (select * from {{ ref("sfdc_opportunitylineitem") }}),
    final as (
        select
            /* primary key */
            opp.opportunity_id,

            /* foreign key */
            opp.account_id,
            opp.record_type_id,
            opp.create_by_id,
            opp.last_modified_by_id,
            opp.owner_id,
            opp.price_book_id,
            opp.campaign_id,
            opp.salesforce_18_digit_id,
            
            /* timestamps */
            opp.created_at_et,
            opp.last_modified_date_et,
            opp.edw_load_datetime_et,
            opp.close_date_et,

            /* status and properties */
            opp.name,
            opp.description,
            opp.stage,
            opp.amount,
            opp.type,
            opp.expected_amount,
            opp.total_quantity,
            opp.lead_source,
            opp.closed,
            opp.is_won,
            opp.forecast_category,
            opp.forecast_category_name,
            opp.currency_iso_code,
            opp.has_line_item,
            opp.is_split,
            opp.system_modstamp,
            opp.last_activity,
            opp.fiscal_quarter,
            opp.fiscal_year,
            opp.fiscal_period,
            opp.last_viewed_date,
            opp.last_referenced_date,
            opp.has_overdue_task,
            opp.product_type,
            opp.usage_type,
            opp.partner_level,
            opp.partner,
            opp.contract_period,
            opp.second_yr_amount,
            opp.third_yr_amount,
            opp.multi_year_amount,
            opp.asset,
            opp.transfer_ownership_to_account_manager,
            opp.downtick_value,
            opp.product_description,
            opp.renewal_expiration_date,
            opp.fastalert,
            opp.visual_command_center_amount,
            opp.is_it_alerting_deal,
            opp.is_emergency_notification_deal,
            opp.is_visual_command_center_deal,
            opp.is_safety_connection_deal,
            opp.ums_lead_source,
            opp.ums_est_close_date,
            opp.ums_type,
            opp.ums_stage,
            opp.ums_product_delivery_mode,
            opp.ums_product,
            opp.ums_establishment_cost,
            opp.ums_annual,
            opp.ums_establishment_plus_annual,
            opp.ums_total_cost,
            opp.ums_actual_revenue,
            opp.ums_training_cost,
            opp.ums_total_amount,
            opp.ums_contact,
            opp.growth_type,
            opp.opportunity_account_manager_manager,
            opp.opportunity_account_manager,
            opp.smt_report_approved_date,
            opp.qfa_date,
            opp.is_budgeted,
            opp.is_what_who_could_stop_this,
            opp.time_bound_incentive,
            opp.incentive_details,
            opp.owner_manager_email,
            opp.running_user_oppty_account_manager,
            opp.smt_report_comments,
            opp.expected_revenue,
            opp.partner_notes,
            opp.oppty_correction_escalation_date_time,
            opp.oppty_corrections_completed_date_time,
            opp.owner_department_vp_email,
            opp.pending_legal_approval1,
            opp.prorating_issue1,
            opp.sales_ops_reviewed,
            opp.signed_amendment,
            opp.signed_msa__if_applicable,
            opp.account_product_region,
            opp.proposed_account_product_region,
            opp.annual_bookings_amount_new_growth,
            opp.total_oppty_annual_booking_amount,
            opp.risk_intelligence_amount,
            opp.crisis_management_amount,
            opp.no_of_ps_products_sold,

            oli.id as line_item_id,
            oli.pricebook_entry_id,
            oli.product_id,
            oli.product_code,
            oli.name as opportunity_product_name,
            oli.quantity,
            oli.totalprice as total_price,
            oli.unitprice as sales_price,
            oli.listprice as list_price,
            oli.description as line_description,
            oli.created_by_id as li_created_by_id,
            oli.last_modified_date_et as li_last_modified_date,
            oli.lastmodified_by_id as li_last_modified_by_id,
            oli.is_deleted as li_deleted,
            oli.annual_fee,
            oli.product_sale_type,
            oli.product_discount_percent,
            oli.fee_type,
            oli.product_family_2,
            oli.opp_product_owner_vp_sales,
            oli.opportunity_stage,
            oli.active_product as is_active_product,
            oli.annual_bookings_amount_r_w,
            oli.quote_product_sales_type

        from opp as opp
        inner join oli as oli on opp.salesforce_18_digit_id = oli.opportunity_id
    )

select * from final
